name: Curse
main: me.hgilman.Curse.Curse
version: 1.0.1
commands:
   curse:
      description: Makes the player's life... unpleasant.
      permission: curse.curse
      permission-message: You dont't have permission to curse someone
      usage: /<command> <player>
